### ISSUE TITLE
DB変更点

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/ANDEN-ADLIV#22]
①M002品番マスタ
　⇒標準重量、許容誤差＋、許容誤差－の項目削除
②M005重量構成マスタの新規追加
③V005品番マスタビューの標準重量、許容誤差＋、許容誤差－の項目取得先変更
④R003重量照合履歴
　⇒重量エラー理由の項目を追加
⑤M001コードマスタの項目に「重量構成区分」を追加
⑥コードマスタの項目の照合結果区分の内容を修正

**Comment by jms-arai** [comment]
①D001ステータス管理に整理Noを追加
　※次かんばんを読ませた状態でいったん終了し、再度画面表示した際にデータの読取元が
　　存在しないため
②V006ステータスチェックビューを追加
　※主に重量チェックに活用
