### ISSUE TITLE
その他不具合

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/ANDEN-ADLIV#24]
- [x] １．取消処理を実施した後に、ＢＨＴにて違うかんばんＱＲを読んでも、ラベルが発行されない
　　⇒　プログラムを再起動するとラベルが発行される
- [x] 2．最後のラベルを読取った時にラベル照合枚数がカウントアップされない
　　　bhtの処理は照合終了しているがpcはの発行枚数＞照合枚数の状態
　　⇒　途中で違うラベルを読んだり、二重で読んだりしたりした
![image](https://user-images.githubusercontent.com/37360243/50073384-c5f43800-021b-11e9-9a23-e846db689efd.png)

**Comment by jms-arai** [comment]
１．に関して、取り消し後にかんばん読み取りのタイマーを止めたままとしていました。
２．に関して、BHTから送られた照合ファイルを読み取り中に、さらにBHTから照合ファイルが
　　送られた場合、最初に処理したファイルをバックアップする際にまだ未処理のファイルも
　　バックアップしてしまっていました。結果、一部のファイルが照合処理されずにバックアップされてしまっていました
